src/Entity/Contact.php
<?php

namespace App\Entity;

use App\Repository\ContactRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ContactRepository::class)
 */
class Contact
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="integer")
     */
    private $phone_number;

    /**
     * @ORM\Column(type="text")
     */
    private $message;

    /**
     * @ORM\Column(type="boolean") 
     */
    private $caseRgpd;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPhoneNumber(): ?int
    {
        return $this->phone_number;
    }

    public function setPhoneNumber(int $phone_number): self
    {
        $this->phone_number = $phone_number;

        return $this;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(string $message): self
    {
        $this->message = $message;

        return $this;
    }

    public function getCaseRgpd(): ?bool
    {
        return $this->caseRgpd;
    }

    public function setCaseRgpd(bool $caseRgpd): self
    {
        $this->caseRgpd = $caseRgpd;

        return $this;
    }
}

src/Controller/Front/ArticleController.php
<?php

namespace App\Controller\Front;

use App\Repository\ArticleRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class ArticleController extends AbstractController 
{

    /**
     * @Route("home/article/{id}", name="article_show")
     */
    public function article(ArticleRepository $articleRepository, $id)
    {
        $article = $articleRepository->find($id);
        $articles = $articleRepository->findAll();

        return $this->render('front/article.html.twig', [
            'article' => $article,
            'articles' => $articles
        ]);
    }

    /**
     * @Route("articles", name="articles")
     */
    public function articles()
    {
        return $this->render('front/article.html.twig');
    }
}

src/Controller/Front/ContactController.php
<?php

namespace App\Controller\Front;

use App\Entity\Contact;
use App\Form\ContactType;
use App\Repository\ContactRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("contact")
 */
class ContactController extends AbstractController 
{
    /**
     * @Route("/new", name="contact_new")
     */
    public function newContact(ContactRepository $contactRepository, Request $request, EntityManagerInterface $entityManagerInterface)
    {

        $message = new Contact();
        $contactForm = $this->createForm(ContactType::class, $message);
        $contactForm->handleRequest($request);

        if($contactForm->isSubmitted() && $contactForm->isValid()) {

            $entityManagerInterface->persist($message);
            $entityManagerInterface->flush();

            return $this->redirectToRoute('contact_new');
        }

        return $this->render('front/contact.html.twig', ['contactForm' => $contactForm->createView()]);
    }
}

src/Controller/Front/HomeController.php
<?php

namespace App\Controller\Front;

use App\Repository\ArticleRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends AbstractController 
{
    /**
     * @Route("/home", name="home")
     */
    public function home(ArticleRepository $articleRepository)
    {
        $articles = $articleRepository->findAll();
        
        return $this->render('front/home.html.twig', ['articles' => $articles]);
    }

    /**
     * @Route("who", name="who")
     */
    public function who()
    {
        return $this->render('front/who.html.twig');
    }

    /**
     * @Route("admin", name="admin")
     */
    public function admin()
    {
        return $this->render('admin/admin.html.twig');
    }
}

src/Controller/Front/ReservationsController.php
<?php

namespace App\Controller\Front;

use App\Entity\Reservations;
use App\Form\ReservationsType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ReservationsController extends AbstractController
{
    /**
     * @Route("reservations/new", name="new_reservation")
     */
    public function newReservation(Request $request, EntityManagerInterface $entityManagerInterface)
    {
        $reservation = new Reservations();
        $reservationForm = $this->createForm(ReservationsType::class, $reservation);
        $reservationForm->handleRequest($request);
        
        if($reservationForm->isSubmitted() && $reservationForm->isValid()) {

            $entityManagerInterface->persist($reservation);
            $entityManagerInterface->flush();

            return $this->redirectToRoute('home');
        }

        return $this->render('front/reservations.html.twig', ['reservationForm' => $reservationForm->createView()]);
    }
}

templates/front/add_user.html.twig
{% block main %}
    <main>
        <h2>Ajouter utilisateur</h2>
        <section>
            <article>
                {{ form_start(userForm) }}
                    {{ form_widget(userForm.name) }}
                    {{ form_widget(userForm.firstName) }}
                    {{ form_widget(userForm.email) }}
                    {{ form_widget(userForm.password) }}
                    {{ form_widget(userForm.submit) }}
                {{ form_end(userForm) }}
            </article>
        </section>
    </main>
{% endblock %}

templates/front/article.html.twig
{% extends "base.html.twig" %}

{% block main %}
    <div class="article-box">
        <section class="one_article">
            <article>
                <div class="article-header">
                    <a href="{{ path('home') }}"><--</a>
                    <h3>{{ article.title }}</h3>
                </div>
                <div>
                    <img src="/images/photo.jpeg" alt="">
                </div>
                <p>{{ article.description }}</p>
            </article>
        </section>

        <aside>
            <h2>Article récents</h2>

            <hr>

            {% for article in articles %}
                <article>
                    <h5>{{ article.title }}</h5>

                    <div>
                        <img src="/images/photo.jpeg" alt="">
                    </div>

                    <a href="{{ path('article_show', {'id' : article.id}) }}">Voir l'article</a>
                </article>
            {% endfor %}
        </aside>
    </div>
{% endblock %}

templates/front/contact.html.twig
{% extends "base.html.twig" %}

{% block main %}
    <h2>Laissez-moi un message !</h2>

    {{ form_start(contactForm) }}
        {{ form_widget(contactForm.name) }}
        {{ form_widget(contactForm.email) }}
        {{ form_widget(contactForm.phone_number) }}
        {{ form_widget(contactForm.message) }}
        {{ form_widget(contactForm.caseRgpd) }}
        {{ form_label(contactForm.caseRgpd, 
            'En cochant cette case, j\'accepte que les informations renseigner dans ce formulaire soient recueillies 
            et utilisées par la société afin que je puisse être contacter. '
        ) }}
        {{ form_widget(contactForm.submit) }}
    {{ form_end(contactForm) }}
{% endblock %}

templates/front/home.html.twig
{% extends "base.html.twig" %}

{% block main %}
    <div class="article-box">
        <section class="all-articles">
            <h2>Tous les articles</h2>
            {# {{ maVariable }} #}

            <hr>  

            {% for article in articles %}
                <article>
                    <h3>{{ article.title }}</h3>

                    <div>
                        <img src="/{{ article.imgUrl }}" alt="">
                    </div>

                    <a href="{{  path('article_show', {'id' : article.id}) }}" class="show_article">Voir l'article</a>
                </article>
            {% endfor %}
        </section>

        <aside>
            <h2>Article récents</h2>

            <hr>

            {% for article in articles %}
                <article>
                        <h5>{{ article.title }}</h5>

                        <div>
                            <img src="/images/photo.jpeg" alt="">
                        </div>

                        <a href="{{  path('article_show', {'id' : article.id}) }}" class="show_article">Voir l'article</a>
                    </article>
            {% endfor %}
        </aside>
    </div>
{% endblock %}

templates/front/reservations.html.twig
{% extends "base.html.twig" %}

{% block main %}
    {{ form_start(reservationForm) }}
        {{ form_widget(reservationForm.firstName) }}
        {{ form_widget(reservationForm.name) }}
        {{ form_widget(reservationForm.meetDate) }}
        {{ form_widget(reservationForm.phoneNumber) }}
        {{ form_widget(reservationForm.topic) }}
        {{ form_widget(reservationForm.submit) }}
    {{ form_end(reservationForm) }}
{% endblock %}

templates/front/who.html.twig
{% extends "base.html.twig" %}

{% block header %}
    <header>
        <nav>
            <ul class="w-50">
                <li class="w-50">
                    <a href="{{ path('home') }}">Accueil</a>
                </li>
                <li class="w-50">
                    <a href="">Réserver</a>
                </li>
            </ul>
            <ul class="w-50">
                <li class="w-50">
                    <a href="{{ path('contact_new') }}">Contact</a>
                </li>
                <li class="w-50">
                    <a href="{{ path('who') }}">Qui suis-je ?</a>
                </li>
            </ul>
        </nav>
    </header>
{% endblock %}

{% block main %}
    <section class="who">
        <h2>Qui suis-je ?</h2>

        <article>
            <div>
                <img src="/images/photo.jpeg" alt="">
            </div>
            <p class="para-1">
                Je me suis réveillée un jour en réalisant que la vie que j’avais ne me rendait pas heureuse.
                <br>
                Et ce malgré ma situation professionnelle dans la finance et les perspectives qu’elle pouvait m’offrir.
                <br>
                Je me suis demandée alors pourquoi je ne suis pas satisfaite ? j’ai pourtant toujours voulu bien faire, on m’a toujours appris à chercher les meilleures opportunités, à chercher la protection et la sécurité… 
                <br>
                En fait là était tout le problème, ce sont ces deux dernières croyances, ancrées depuis le début de mon éducation qui m’ont fait faire des choix sans trop consulter mon avis profond qui lui, a parfois exprimé le contraire mais qui finalement se résigne à écouter « la voix de la raison ».

                <br>
                <br>

                Mais Pourquoi étais-je tant convaincue qu’absolument tout ce qu’on a pu me dire ou m’apprendre à plus de crédibilité et de valeur que ce que je pense au fond ? Parce que ça répondrait a mes croyances ? Que ça mettrait ma famille à l’abri ? que je serai tranquille ? Que ça correspondait aux bons critères de la société ? Que ça me faisait rentrer dans le moule ?
                <br>
                Cette base de pensée erronée, ancrée, rendait tous mes rêves « risqués ».
                <br>
                J’ai donc écouté plus attentivement mon « moi intérieur », et considéré que le risque était de ne pas vivre la vie que je voulais.
                <br>
                Je me suis répétée que je risquais de ne pas vivre mes rêves si je ne sortais pas de ce schéma, la vie passe trop vite et j’ai osé.
                <br>
                J’ai osé écouter totalement mes envies profondes, aussi folles soient-elles. J’ai toujours eu envie de courir un marathon…
                <br>
                C’est fait! Et j’y ai pris goût! J’ai toujours voulu être mon propre patron, j’ai donc décidé de tout plaquer, de sortir des sentiers battus pour avoir enfin cette incommensurable satisfaction de faire ce qui me plait! Pour moi c’est ça la vie, prendre des risques, sortir de sa « zone de confort » qui en réalité n’en est pas une.
                <br>
                <br>
                Les années passent trop vite pour se résigner à laisser ses envies au stade de rêve.
            </p>

            <p class="para-2">
                Vous pouvez me retouver sur mes réseaux pour en apprendre plus sur moi !
            </p>
            <nav>
                <ul>
                    <li>
                        <a href="https://www.instagram.com/jessicachievement/?hl=fr" target="_blank">Instagram</a>
                    </li>
                    <li>
                        <a href="">LinkedIn</a>
                    </li>
                    <li>
                        <a href="">Facebook</a>
                    </li>
                </ul>
            </nav>
        </article>
    </section>
{% endblock %}